system:
    t_max: 10000
    output_flag: true
    
    output:
        every: 200
        path: ../Data
    
general:
    seed: 110
    dt: 0.05
    dimension: 2
    L: 1000.0

motiles:
    density: 0.0002
    v_0: 10.0
    tumble_flag: false
    force_flag: true
    noise_flag: true

    noise:
        D_rot: 0.01

    force:
        sensitivity: 100.0

    tumble:
        p_0: 1.0
        chemotaxis_alg: grad
        
        grad:
            sensitivity: 10.0
field:
    dx: 4.0
    f_0: 1.0
    f_pde_flag: true
    c_pde_flag: true
    obstructions_alg: parametric

    obstructions:
        traps:
            n: 5
            width: 100.0
            thickness: 20.0
            slit_width: 8.0

        parametric:
            n: 6
            stickiness: 10.0
            radius_min: 20.0
            radius_max: 60.0
            
    f_pde:
        D: 20.0
        sink_rate: 10.0
            
    c_pde:
        D: 20.0
        sink_rate: 0.01
        source_rate: 1
